# Your Name or Company
title: Ko Ko Ye

# Description of your website. This is used for social sharing.
description: Ko Ko Ye, kokoye2007 Personal Blog

# A brief blurb about yourself
content: "I have played around with Linux since 2004, from Web Designer to  Web Administrator (For LAMP) with Ubuntu being my main choice.  I settled on Ubuntu as my favourite Linux distro. I will Promote About Linux and Ubuntu Distro since 2009., Raspberry Pi since 2013, Container LXD at 2014, Open Stack at 2016, DevOps at 2018, Docker and Kubernetes at 2019."

# Half layout options
#half_side: left
#half_image: woman-half.jpg

# Add your social links
social:
  - platform: github
    url: https://github.com/kokoye2007
  - platform: Mastodon
    url: https://burma.social/@kokoye2007
  - platform: facebook
    url: https://facebook.com/kokoye2007
  - platform: twitter
    url: https://twitter.com/kokoye2007
  - platform: linkedin
    url: https://www.linkedin.com/in/kokoye2007
  - platform: ubuntu
    url: https://wiki.ubuntu.com/kokoye2007
  - platform: project
    url: https://kokoye2007.github.io/project
  - platform: resume
    url: https://kokoye2007.github.io/cv

# General settings
url: https://kokoye2007.github.io
#baseurl: "/kokoye2007"
markdown: kramdown
sharing_image: share.jpg
#google_analytics: "UA-58263416-1" # google analytics tracking
permalink: pretty

#### LAYOUT OPTIONS #####

# Half layout
half_side: right 

# Full layout
full_text_position: left # left, right or center
